spring:

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${JDBC_URL:jdbc:oracle:thin:@localhost:1521:xe}
    username: ${DB_USERNAME:moon}
    password: ${DB_PASSWORD:pass}

  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE